import type { Event, Sale, Revenue, Payout } from './types';

export const upcomingEvents: Event[] = [
  {
    id: 'winter-wonderfest',
    name: 'Winter Wonderfest',
    date: '2024-01-20',
    location: 'Millennium Park, Chicago',
    ticketsSold: 2500,
    totalTickets: 3000,
    imageUrl: 'https://picsum.photos/seed/event5/600/400',
    price: 45,
  },
  {
    id: 'spring-bloom-festival',
    name: 'Spring Bloom Festival',
    date: '2024-04-05',
    location: 'Brooklyn Botanic Garden, New York',
    ticketsSold: 1800,
    totalTickets: 2000,
    imageUrl: 'https://picsum.photos/seed/event6/600/400',
    price: 60,
  },
  {
    id: 'indie-film-showcase',
    name: 'Indie Film Showcase',
    date: '2024-06-12',
    location: 'TCL Chinese Theatre, Hollywood',
    ticketsSold: 450,
    totalTickets: 500,
    imageUrl: 'https://picsum.photos/seed/event7/600/400',
    price: 25,
  },
  {
    id: 'summer-music-festival',
    name: 'Summer Music Festival',
    date: '2024-08-15',
    location: 'Central Park, New York',
    ticketsSold: 4500,
    totalTickets: 5000,
    imageUrl: 'https://picsum.photos/seed/event1/600/400',
    price: 75,
  },
  {
    id: 'tech-conference-2024',
    name: 'Tech Conference 2024',
    date: '2024-09-10',
    location: 'Moscone Center, San Francisco',
    ticketsSold: 1200,
    totalTickets: 1500,
    imageUrl: 'https://picsum.photos/seed/event2/600/400',
    price: 499,
  },
  {
    id: 'art-wine-fair',
    name: 'Art & Wine Fair',
    date: '2024-09-22',
    location: 'Napa Valley, California',
    ticketsSold: 350,
    totalTickets: 400,
    imageUrl: 'https://picsum.photos/seed/event3/600/400',
    price: 120,
  },
  {
    id: 'marathon-of-hope',
    name: 'Marathon of Hope',
    date: '2024-10-05',
    location: 'City Waterfront',
    ticketsSold: 8000,
    totalTickets: 10000,
    imageUrl: 'https://picsum.photos/seed/event4/600/400',
    price: 50,
  },
  {
    id: 'oktoberfest-celebration',
    name: 'Oktoberfest Celebration',
    date: '2024-10-15',
    location: 'Old World Village, Huntington Beach',
    ticketsSold: 3000,
    totalTickets: 3500,
    imageUrl: 'https://picsum.photos/seed/event8/600/400',
    price: 30,
  },
];

export const draftEvents: Event[] = [
  {
    id: 'untitled-charity-run',
    name: 'Untitled Charity Run',
    date: '2024-11-15',
    location: 'Venue TBD',
    ticketsSold: 0,
    totalTickets: 500,
    imageUrl: 'https://picsum.photos/seed/draft1/600/400',
  },
  {
    id: 'annual-tech-summit',
    name: 'Annual Tech Summit',
    date: '2024-12-01',
    location: 'Convention Center',
    ticketsSold: 0,
    totalTickets: 1000,
    imageUrl: 'https://picsum.photos/seed/draft2/600/400',
  },
];

export const salesData: Sale[] = [
  { month: 'Jan', sales: 4000 },
  { month: 'Feb', sales: 3000 },
  { month: 'Mar', sales: 5000 },
  { month: 'Apr', sales: 4500 },
  { month: 'May', sales: 6000 },
  { month: 'Jun', sales: 5500 },
  { month: 'Jul', sales: 7000 },
];

export const revenueData: Revenue[] = [
  { month: 'Jan', revenue: 6500 },
  { month: 'Feb', revenue: 5900 },
  { month: 'Mar', revenue: 8000 },
  { month: 'Apr', revenue: 8100 },
  { month: 'May', revenue: 5600 },
  { month: 'Jun', revenue: 7200 },
  { month: 'Jul', revenue: 7850 },
  { month: 'Aug', revenue: 6800 },
  { month: 'Sep', revenue: 9000 },
  { month: 'Oct', revenue: 9500 },
  { month: 'Nov', revenue: 7300 },
  { month: 'Dec', revenue: 10200 },
];

export const payoutHistory: Payout[] = [
  {
    id: 'payout-1',
    date: '2024-07-01',
    amount: 5200.0,
    method: 'Bank Transfer',
    status: 'Completed',
  },
  {
    id: 'payout-2',
    date: '2024-06-15',
    amount: 4800.0,
    method: 'PayPal',
    status: 'Completed',
  },
  {
    id: 'payout-3',
    date: '2024-06-01',
    amount: 7500.5,
    method: 'Bank Transfer',
    status: 'Completed',
  },
  {
    id: 'payout-4',
    date: '2024-05-15',
    amount: 3200.0,
    method: 'Bank Transfer',
    status: 'Completed',
  },
  {
    id: 'payout-5',
    date: '2024-05-01',
    amount: 6100.25,
    method: 'PayPal',
    status: 'Completed',
  },
  {
    id: 'payout-6',
    date: '2024-04-15',
    amount: 2500.0,
    method: 'Bank Transfer',
    status: 'Failed',
  },
];